extends Object


# Cost of each summon. Also source of truth for every available summon
const SUMMON_COSTS := {
  "imp": {
    "mana": 50
  },
  "hellcat": {
    "mana": 50,
    "gems": 20
  }
}

# Base resources generated by each summon per tick
const BASE_GEN := {
  "imp": {
    "gems": 1
  }
}

# Base demon power provided by entities
const BASE_DEMON_POWER := {
  "hellcat": 2
}
